output_path: ./data/output

LLM:
  title_model:
    LLM_API_KEY: ***
    LLM_BASE_URL: https://dashscope.aliyuncs.com/compatible-mode/v1
    LLM_MODEL: qwen3-14b
  img:
    API_KEY : ***
    BASE_URL : https://dashscope.aliyuncs.com/compatible-mode/v1
    MODEL : qwen3-vl-8b-instruct
  table:
    API_KEY : ***
    BASE_URL : https://dashscope.aliyuncs.com/compatible-mode/v1
    MODEL : qwen3-14b
img_enable: true
table_enable: true

