output_path: ./data/output
output_path_temp: ./data/temp
LLM:
  title_model:
    LLM_API_KEY: sk-1fdbb0e4ce3943bab4b300ca867c1315
    LLM_BASE_URL: https://dashscope.aliyuncs.com/compatible-mode/v1
    LLM_MODEL: qwen3-14b
    connection_timeout: 20
    process_timeout: 600
  img:
    API_KEY : sk-1fdbb0e4ce3943bab4b300ca867c1315
    BASE_URL : https://dashscope.aliyuncs.com/compatible-mode/v1
    MODEL : qwen3-vl-8b-instruct
    connection_timeout: 20
    process_timeout: 180
  table:
    API_KEY : sk-1fdbb0e4ce3943bab4b300ca867c1315
    BASE_URL : https://dashscope.aliyuncs.com/compatible-mode/v1
    MODEL : qwen3-14b
    connection_timeout: 20
    process_timeout: 300
  red_title:
    API_KEY : sk-1fdbb0e4ce3943bab4b300ca867c1315
    BASE_URL : https://dashscope.aliyuncs.com/compatible-mode/v1
    MODEL : qwen3-vl-32b-instruct
    connection_timeout: 20
    process_timeout: 180
MinIO:
  IP: 60.204.211.83:10000
  ACCESS_KEY: minioadmin
  SECRET_KEY: minioadmin123
  BUCKET_NAME: preprocess

